"use strict";
const DATA=window.BERRY_DATA||{};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE_KEY="berryVibesCCD2026_v5_3D", AUTH_USERS_KEY="berryVibesUsers_v3", AUTH_SESSION_KEY="berryVibesSession_v3";
const IMAGE={
  sweet:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=82",
  chocolate:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=82",
  coffee:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=82",
  donut:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1000&q=82",
  savory:"https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1000&q=82",
  sandwich:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=82",
  bowl:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=82",
  snack:"https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1000&q=82",
  movement:"https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1000&q=82"
};
const MOVEMENTS=[
  {id:"walk",name:"GENTLE WALK",emoji:"🚶🏽‍♀️",rate:3.4,copy:"EASY, STEADY MOVEMENT WITH A SIMPLE AUTO BURN ESTIMATE."},
  {id:"campus",name:"CAMPUS / EVERYDAY WALK",emoji:"🎒",rate:3.8,copy:"EVERYDAY WALKING WITH A SLIGHTLY BRISKER ESTIMATE."},
  {id:"yoga",name:"YOGA",emoji:"🧘🏽‍♀️",rate:2.6,copy:"MOBILITY, CONTROL, BALANCE, AND BREATHING."},
  {id:"barre",name:"BARRE",emoji:"🩰",rate:3.5,copy:"SMALL CONTROLLED MOVES, BALANCE, AND MUSCLE ENDURANCE."},
  {id:"dance",name:"JUST DANCE / MICHAEL JACKSON: THE EXPERIENCE",emoji:"🕺🏽",rate:5.6,copy:"THE PLAYFUL CARDIO OPTION — MUSIC ON, ARCADE ENERGY UP."},
  {id:"pilates",name:"PILATES",emoji:"✨",rate:3.2,copy:"CONTROLLED CORE-FOCUSED MOVEMENT WITH STEADY PACING."},
  {id:"strength",name:"STRENGTH TRAINING",emoji:"🏋🏽‍♀️",rate:4.2,copy:"RESISTANCE WORK WITH A MODERATE SESSION ESTIMATE."},
  {id:"incline",name:"INCLINE TREADMILL",emoji:"⛰️",rate:6.0,copy:"UPHILL CARDIO WITH A HIGHER PER-MINUTE ESTIMATE."},
  {id:"elliptical",name:"ELLIPTICAL",emoji:"💫",rate:5.2,copy:"SMOOTH LOW-IMPACT CARDIO WITH STEADY RHYTHM."},
  {id:"mobility",name:"STRETCH + MOBILITY",emoji:"🌷",rate:2.0,copy:"GENTLE RANGE-OF-MOTION WORK AND RECOVERY MOVEMENT."}
];
const BERRY_BRUNCH_CHARACTERS=[
  {id:"rosette",image:"assets/characters/rosette.jpg",name:"ROSETTE",emoji:"🍓🧚🏽‍♀️",tone:"PINK / RED",role:"STRAWBERRY-PASTRY FAIRY · WARMTH, LOVE + EXCITEMENT · MAIN GUIDE"},
  {id:"zing",image:"assets/characters/zing.png",name:"ZING",emoji:"🍊⚡",tone:"ORANGE / YELLOW",role:"TINY CITRUS CANDY COURIER · ENERGY + OPTIMISM · SPEED BOOSTER"},
  {id:"mallow",image:"assets/characters/mallow.png",name:"MALLOW",emoji:"☁️💜",tone:"LAVENDER",role:"SQUISHY MARSHMALLOW-CLOUD · IMAGINATION + CALM · SHIELD / HELP"},
  {id:"sourpop",image:"assets/characters/sourpop.png",name:"SOURPOP",emoji:"🐉💚",tone:"GREEN",role:"MISCHIEVOUS GUMMY DRAGON · FRESHNESS + MISCHIEF · CLEARS OBSTACLES"},
  {id:"truffle",image:"assets/characters/truffle.png",name:"TRUFFLE",emoji:"🍫🤎",tone:"BROWN / CREAM",role:"CHUNKY CHOCOLATE-TRUFFLE CREATURE · COMFORT + STABILITY · HEAVY TILE BREAKER"}
];
const SHOP_PRODUCTS=[
  {id:"rosette-plush",character:"ROSETTE",name:"ROSETTE STRAWBERRY-PASTRY PLUSH",category:"PLUSH",price:24.00,image:"assets/characters/rosette.jpg",desc:"A SOFT PINK CHARACTER-PLUSH CONCEPT INSPIRED BY ROSETTE'S WARM, EXCITED MAIN-GUIDE ENERGY."},
  {id:"rosette-pin",character:"ROSETTE",name:"ROSETTE ENAMEL PIN",category:"PINS",price:8.50,image:"assets/characters/rosette.jpg",desc:"A SMALL BERRY-BRUNCH PIN CONCEPT FOR ROSETTE FANS."},
  {id:"rosette-card",character:"ROSETTE",name:"ROSETTE CHARACTER CARD",category:"CARDS",price:5.00,image:"assets/characters/rosette.jpg",desc:"A COLLECTIBLE CHARACTER-CARD CONCEPT WITH ROSETTE'S GUIDE ROLE AND COLOR STORY."},
  {id:"zing-keychain",character:"ZING",name:"ZING CITRUS KEYCHAIN",category:"KEYCHAINS",price:10.00,image:"assets/characters/zing.png",desc:"A BRIGHT ORANGE KEYCHAIN CONCEPT BUILT AROUND ZING'S SPEEDY COURIER VIBE."},
  {id:"zing-figure",character:"ZING",name:"ZING DESK FIGURE",category:"FIGURES",price:18.00,image:"assets/characters/zing.png",desc:"A TINY DESK-FIGURE CONCEPT FOR THE FASTEST LITTLE CITRUS CANDY COURIER."},
  {id:"zing-phone",character:"ZING",name:"ZING PHONE CHARM",category:"CHARMS",price:9.00,image:"assets/characters/zing.png",desc:"AN ORANGE-YELLOW PHONE-CHARM CONCEPT WITH BOUNCY SPEED-BOOSTER ENERGY."},
  {id:"mallow-plush",character:"MALLOW",name:"MALLOW CLOUD PLUSH",category:"PLUSH",price:26.00,image:"assets/characters/mallow.png",desc:"A SQUISHY LAVENDER PLUSH CONCEPT INSPIRED BY MALLOW'S CALM, HELPFUL SHIELD ENERGY."},
  {id:"mallow-charm",character:"MALLOW",name:"MALLOW BAG CHARM",category:"CHARMS",price:11.00,image:"assets/characters/mallow.png",desc:"A SOFT-COLOR BAG CHARM CONCEPT FOR THE IMAGINATION-AND-CALM CHARACTER."},
  {id:"mallow-card",character:"MALLOW",name:"MALLOW CHARACTER CARD",category:"CARDS",price:5.00,image:"assets/characters/mallow.png",desc:"A COLLECTIBLE CHARACTER-CARD CONCEPT FEATURING MALLOW'S SUPPORT ROLE."},
  {id:"sourpop-figure",character:"SOURPOP",name:"SOURPOP GUMMY DRAGON FIGURE",category:"FIGURES",price:21.00,image:"assets/characters/sourpop.png",desc:"A GREEN DESK-FIGURE CONCEPT FOR THE MISCHIEVOUS GUMMY DRAGON WHO CLEARS OBSTACLES."},
  {id:"sourpop-pin",character:"SOURPOP",name:"SOURPOP DRAGON PIN",category:"PINS",price:8.50,image:"assets/characters/sourpop.png",desc:"A PLAYFUL GREEN ENAMEL-PIN CONCEPT WITH SOURPOP'S CHAOTIC LITTLE GRIN ENERGY."},
  {id:"sourpop-sticker",character:"SOURPOP",name:"SOURPOP STICKER PACK",category:"STICKERS",price:7.00,image:"assets/characters/sourpop.png",desc:"A SMALL CHARACTER-STICKER PACK CONCEPT BUILT AROUND SOURPOP'S FRESH, MISCHIEVOUS VIBE."},
  {id:"truffle-plush",character:"TRUFFLE",name:"TRUFFLE CHOCOLATE CREATURE PLUSH",category:"PLUSH",price:27.00,image:"assets/characters/truffle.png",desc:"A CHUNKY BROWN-AND-CREAM PLUSH CONCEPT INSPIRED BY TRUFFLE'S COMFORTING, STEADY ENERGY."},
  {id:"truffle-figure",character:"TRUFFLE",name:"TRUFFLE HEAVY-HITTER FIGURE",category:"FIGURES",price:22.00,image:"assets/characters/truffle.png",desc:"A SOLID DESK-FIGURE CONCEPT FOR THE BERRY-BRUNCH HEAVY TILE BREAKER."},
  {id:"truffle-tote",character:"TRUFFLE",name:"TRUFFLE COZY TOTE",category:"TOTES",price:19.00,image:"assets/characters/truffle.png",desc:"A WARM BROWN-AND-CREAM TOTE CONCEPT WITH TRUFFLE'S COMFORT-AND-STABILITY VIBE."},
  {id:"brunch-blindbox",character:"BERRY BRUNCH",name:"BERRY BRUNCH MINI BLIND BOX",category:"BLIND BOX",price:14.00,image:"assets/characters/berry-vibes-cast.png",desc:"A SURPRISE MINI-FIGURE CONCEPT FEATURING ROSETTE, ZING, MALLOW, SOURPOP, OR TRUFFLE."},
  {id:"brunch-sticker-set",character:"BERRY BRUNCH",name:"BERRY BRUNCH FULL CAST STICKERS",category:"STICKERS",price:9.00,image:"assets/characters/berry-vibes-cast.png",desc:"A FIVE-CHARACTER STICKER-SET CONCEPT WITH THE WHOLE BERRY BRUNCH CREW."},
  {id:"brunch-tote",character:"BERRY BRUNCH",name:"BERRY BRUNCH CAST TOTE",category:"TOTES",price:22.00,image:"assets/characters/berry-vibes-cast.png",desc:"A FULL-CAST TOTE CONCEPT — CHARACTER MERCH ONLY, NOT DANIELLE'S DESIGN PORTFOLIO."}
];
const THEMES=[
  {id:"berry",label:"BERRY",bg:"#fff8fb",surface:"#ffffff",surface2:"#fff0f6",accent:"#ff4f8b",accent2:"#7c5cff"},
  {id:"lavender",label:"LAVENDER",bg:"#faf8ff",surface:"#ffffff",surface2:"#f0ebff",accent:"#7c5cff",accent2:"#e04f9c"},
  {id:"peach",label:"PEACH",bg:"#fffaf4",surface:"#ffffff",surface2:"#fff0df",accent:"#f47e58",accent2:"#ff4f8b"},
  {id:"mint",label:"MINT",bg:"#f5fffb",surface:"#ffffff",surface2:"#e8fbf4",accent:"#2da98c",accent2:"#4f86ff"},
  {id:"cocoa",label:"COCOA",bg:"#fffaf7",surface:"#ffffff",surface2:"#f5e9df",accent:"#8b5b46",accent2:"#d28168"},
  {id:"citrus",label:"CITRUS",bg:"#fffdf5",surface:"#ffffff",surface2:"#fff5c9",accent:"#f59e0b",accent2:"#ff6b35"}
];
let selectedLogTime={hour:12,minute:0,period:"PM"};
let recipeVisible=20, factVisible=24, studioIngredients=[];

function defaultState(){return {logs:[],water:0,xp:0,fastHistory:[],activeFast:null,customRestaurants:[],studioRecipes:[],wishlist:[],savedShop:[],cart:[],profile:{name:"",height:"",weight:"",reason:"",theme:"berry",accent:"#ff4f8b",photo:""}}}
function loadState(){try{const base=defaultState(),saved=JSON.parse(localStorage.getItem(STORE_KEY)||"{}");return {...base,...saved,profile:{...base.profile,...(saved.profile||{})}}}catch{return defaultState()}}
let state=loadState();
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function round(v,n=0){const p=10**n;return Math.round((Number(v)||0)*p)/p}
function toast(msg){const el=$("#toast");if(!el)return;el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),1900)}
function nowGreeting(){const h=new Date().getHours();return h<12?"GOOD MORNING":h<17?"GOOD AFTERNOON":h<21?"GOOD EVENING":"GOOD NIGHT"}
function fmtTime(ts){return new Date(ts).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
function fmtDate(ts){return new Date(ts).toLocaleDateString([],{month:"short",day:"numeric"})}
function imageFor(item){if(item?.image)return item.image;const t=((item?.name||"")+" "+(item?.group||"")).toLowerCase();if(/coffee|latte|mocha|drink|hot chocolate/.test(t))return IMAGE.coffee;if(/donut/.test(t))return IMAGE.donut;if(/chocolate|brownie|cake|cookie|oreo|muffin/.test(t))return IMAGE.chocolate;if(/sandwich|burger|bagel|toast|philly/.test(t))return IMAGE.sandwich;if(/bowl|salad|yogurt/.test(t))return IMAGE.bowl;if(/pasta|pizza|chicken|rice|egg|savory|wrap|steak/.test(t))return IMAGE.savory;if(/snack|cracker|candy/.test(t))return IMAGE.snack;return IMAGE.sweet}
function allFoods(){const map=new Map();[...(DATA.CCD_RECIPES||[]),...(DATA.RECOVERED_FOOD_LOGS||[]),...(state.studioRecipes||[])].forEach(x=>{if(x?.id&&!map.has(x.id))map.set(x.id,x)});return [...map.values()]}
function nutritionOf(item){if(item?.nutrition){return {calories:+item.nutrition.calories||0,carbs:+item.nutrition.carbs||0,protein:+item.nutrition.protein||0,fat:+item.nutrition.fat||0,fiber:+item.nutrition.fiber||0,estimated:false}}
  const c=+item?.calories||220,t=((item?.name||"")+" "+(item?.group||"")).toLowerCase();let protein=.17,carbs=.50,fat=.30,fiber=Math.max(1,c/110);
  if(/chicken|steak|egg|cheese|yogurt|cottage/.test(t)){protein=.28;carbs=.35;fat=.32} if(/cake|brownie|cookie|donut|chocolate/.test(t)){protein=.08;carbs=.55;fat=.34} if(/pasta|rice|bread|pancake|oat/.test(t)){protein=.12;carbs=.62;fat=.22}
  return {calories:c,carbs:round(c*carbs/4,1),protein:round(c*protein/4,1),fat:round(c*fat/9,1),fiber:round(fiber,1),estimated:true}
}
function scaleNutrition(n,m=1){return {calories:round(n.calories*m),carbs:round(n.carbs*m,1),protein:round(n.protein*m,1),fat:round(n.fat*m,1),fiber:round(n.fiber*m,1),estimated:n.estimated}}
function tasteFor(item){if(item?.taste)return item.taste;const t=(item?.name||"").toLowerCase();if(/cinnamon|roll|pancake|hotcake/.test(t))return "WARM, SOFT, CINNAMON-COZY, WITH A FLUFFY BREAKFAST-BAKERY VIBE.";if(/chocolate|brownie|oreo|mocha/.test(t))return "DEEP CHOCOLATE, COZY-SWEET, AND DESSERT-LIKE WITHOUT LOSING THE CCD FEEL.";if(/pasta|alfredo|mac/.test(t))return "CREAMY, SAVORY, COMFORTING, AND SAUCE-FORWARD.";if(/chicken|steak|sandwich|philly/.test(t))return "SAVORY, JUICY, TOASTY, AND SATISFYING WITH A HEARTIER BITE.";if(/coffee|latte/.test(t))return "WARM, ROASTY, AROMATIC, AND COZY WITH A SMOOTH FINISH.";return "COZY, BALANCED, FAMILIAR, AND DESIGNED TO FEEL LIKE A FUN COMFORT-FOOD MOMENT."}
function barHtml(label,value,max,unit="G"){const pct=clamp((Number(value)||0)/(max||1)*100,0,100);return `<div class="bar-row"><span>${esc(label)}</span><div class="bar-track"><i style="width:${pct}%"></i></div><b>${round(value,1)}${unit}</b></div>`}
function nutritionCard(n,item){return `<div class="nutrition-card"><div class="nutrition-top"><span>${n.estimated?"ARCHIVE ESTIMATE":"SAVED NUTRITION"}</span><strong>${round(n.calories)} KCAL</strong></div><div class="macro-mini"><div><span>CARBS</span><b>${round(n.carbs,1)}G</b></div><div><span>PROTEIN</span><b>${round(n.protein,1)}G</b></div><div><span>FAT</span><b>${round(n.fat,1)}G</b></div><div><span>FIBER</span><b>${round(n.fiber,1)}G</b></div></div><div class="taste-chart"><span>WHAT TO EXPECT</span><b>${esc(tasteFor(item))}</b></div></div>`}
function foodSelectOptions(items){return items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("")}
function getFood(id){return allFoods().find(x=>x.id===id)}
function setLogTimeNow(){const d=new Date(),h=d.getHours();selectedLogTime={hour:h%12||12,minute:d.getMinutes(),period:h>=12?"PM":"AM"}}
function selectedTimestamp(after=null){const d=new Date();let h=selectedLogTime.hour%12;if(selectedLogTime.period==="PM")h+=12;d.setHours(h,selectedLogTime.minute,0,0);if(after&&d.getTime()<=after)d.setDate(d.getDate()+1);return d.getTime()}
function initTimeDock(){const mount=$("#timeDockMount");if(!mount)return;setLogTimeNow();const buttons=(type,values,format=v=>v)=>`<div class="time-wheel-group"><span>${type}</span><div class="time-wheel-lane" data-lane="${type.toLowerCase()}">${values.map(v=>`<button type="button" data-time-${type.toLowerCase()}="${v}">${format(v)}</button>`).join("")}</div></div>`;mount.className="card time-selector-panel";mount.innerHTML=`<div class="time-selector-copy"><span class="eyebrow">PLAYABLE TIME SCROLLER · NOT A TIMER</span><h2>WHEN DID THIS HAPPEN?</h2><p>SCROLL OR TAP THE HOUR, EXACT MINUTE, AND AM/PM. YOUR NEXT LOG USES THIS TIME.</p><div class="time-readout"><span>SELECTED</span><strong id="timeSelectedLabel">--:--</strong><button id="timeUseNow" class="tiny-btn">USE NOW ✦</button></div></div><div class="time-wheel-grid">${buttons("HOUR",Array.from({length:12},(_,i)=>i+1))}${buttons("MINUTE",Array.from({length:60},(_,i)=>i),v=>String(v).padStart(2,"0"))}${buttons("PERIOD",["AM","PM"])}</div>`;
  $$('[data-time-hour]',mount).forEach(b=>b.onclick=()=>{selectedLogTime.hour=+b.dataset.timeHour;renderTimeDock()});$$('[data-time-minute]',mount).forEach(b=>b.onclick=()=>{selectedLogTime.minute=+b.dataset.timeMinute;renderTimeDock()});$$('[data-time-period]',mount).forEach(b=>b.onclick=()=>{selectedLogTime.period=b.dataset.timePeriod;renderTimeDock()});$("#timeUseNow").onclick=()=>{setLogTimeNow();renderTimeDock();toast("TIME RESET TO NOW ✨")};renderTimeDock()}
function renderTimeDock(){const label=$("#timeSelectedLabel");if(!label)return;label.textContent=`${selectedLogTime.hour}:${String(selectedLogTime.minute).padStart(2,"0")} ${selectedLogTime.period}`;$$('[data-time-hour]').forEach(b=>b.classList.toggle("active",+b.dataset.timeHour===selectedLogTime.hour));$$('[data-time-minute]').forEach(b=>b.classList.toggle("active",+b.dataset.timeMinute===selectedLogTime.minute));$$('[data-time-period]').forEach(b=>b.classList.toggle("active",b.dataset.timePeriod===selectedLogTime.period));requestAnimationFrame(()=>$$('.time-wheel-lane .active').forEach(b=>b.scrollIntoView({block:"center",behavior:"auto"})))}
function applyTheme(){const t=THEMES.find(x=>x.id===state.profile.theme)||THEMES[0],r=document.documentElement.style;r.setProperty("--bg",t.bg);r.setProperty("--surface",t.surface);r.setProperty("--surface-2",t.surface2);r.setProperty("--accent",state.profile.accent||t.accent);r.setProperty("--accent-2",t.accent2)}
function updateAuthChip(){const email=localStorage.getItem(AUTH_SESSION_KEY),el=$("#authChip");if(!el)return;el.textContent=email?"SIGNED IN ✦":"SIGN IN";el.href="login.html"}
function initInteractions(){
  document.addEventListener("click",e=>{if(e.target.closest("button,a,input,select,textarea,dialog"))return;const s=document.createElement("i");s.className="click-spark";s.textContent=["✦","♡","•","✧"][Math.floor(Math.random()*4)];s.style.left=e.clientX+"px";s.style.top=e.clientY+"px";document.body.appendChild(s);setTimeout(()=>s.remove(),700)});
  const orb=$("#draggableBerry"),board=orb?.parentElement;if(orb&&board){let drag=false,ox=0,oy=0;orb.onpointerdown=e=>{drag=true;orb.setPointerCapture(e.pointerId);const r=orb.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;orb.classList.add("dragging")};orb.onpointermove=e=>{if(!drag)return;const r=board.getBoundingClientRect();orb.style.left=clamp(e.clientX-r.left-ox,0,r.width-orb.offsetWidth)+"px";orb.style.top=clamp(e.clientY-r.top-oy,0,r.height-orb.offsetHeight)+"px"};orb.onpointerup=e=>{drag=false;orb.releasePointerCapture?.(e.pointerId);orb.classList.remove("dragging")}};
  const canTilt=matchMedia("(hover:hover) and (pointer:fine)").matches&&!matchMedia("(prefers-reduced-motion: reduce)").matches;
  if(canTilt){document.addEventListener("pointermove",e=>{const card=e.target.closest(".card,.battle-card,.shop-card,.media-card,.character-chip,.motion-token,.mini-character,.berry-stage");if(!card)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty("--tilt-x",`${(-y*5).toFixed(2)}deg`);card.style.setProperty("--tilt-y",`${(x*7).toFixed(2)}deg`);card.classList.add("is-tilting")});document.addEventListener("pointerout",e=>{const card=e.target.closest(".card,.battle-card,.shop-card,.media-card,.character-chip,.motion-token,.mini-character,.berry-stage");if(card&&!card.contains(e.relatedTarget)){card.classList.remove("is-tilting");card.style.removeProperty("--tilt-x");card.style.removeProperty("--tilt-y")}})}
}

function dashboardTotals(){const food=state.logs.filter(x=>x.kind==="food"),moves=state.logs.filter(x=>x.kind==="move");const n=food.reduce((a,x)=>{a.calories+=x.nutrition.calories;a.carbs+=x.nutrition.carbs;a.protein+=x.nutrition.protein;a.fat+=x.nutrition.fat;a.fiber+=x.nutrition.fiber;return a},{calories:0,carbs:0,protein:0,fat:0,fiber:0});return {food,moves,n,burn:moves.reduce((a,x)=>a+x.burn,0)}}
function initDashboard(){const {food,n,burn}=dashboardTotals();$("#greeting").textContent=nowGreeting()+(state.profile.name?`, ${state.profile.name}`:"")+" ✨";$("#calorieTotal").textContent=Math.round(n.calories);$("#waterTotal").textContent=state.water+" OZ";$("#burnTotal").textContent=Math.round(burn);$("#xpTotal").textContent=state.xp+" XP";$("#maintenanceFill").style.width=clamp(n.calories/2150*100,0,100)+"%";$("#macroBars").innerHTML=barHtml("CARBS",n.carbs,250)+barHtml("PROTEIN",n.protein,100)+barHtml("FAT",n.fat,80)+barHtml("FIBER",n.fiber,30);const groups={"GRAINS + BASE":0,"PROTEIN":0,"FRUIT + VEG":0,"FUN + EXTRAS":0};food.forEach(x=>{const t=x.name.toLowerCase();if(/bread|bagel|pancake|oat|flour|rice|pasta|tortilla|pizza/.test(t))groups["GRAINS + BASE"]++;if(/egg|chicken|steak|yogurt|cheese|milk|cottage/.test(t))groups.PROTEIN++;if(/apple|berry|spinach|pumpkin|orange|fruit|veg/.test(t))groups["FRUIT + VEG"]++;if(/chocolate|cookie|cake|donut|sotd|candy|milkshake/.test(t))groups["FUN + EXTRAS"]++});const max=Math.max(1,...Object.values(groups));$("#pyramidBars").innerHTML=Object.entries(groups).map(([k,v])=>barHtml(k,v,max,"×")).join("");renderTimeline($("#todayLog"),state.logs.slice().sort((a,b)=>b.at-a.at).slice(0,14));$$('[data-water]').forEach(b=>b.onclick=()=>{state.water+=+b.dataset.water;state.xp+=3;save();toast(`+${b.dataset.water} OZ WATER 💧`);initDashboard()});$("#resetDay").onclick=()=>{if(confirm("RESET TODAY'S LOGS, WATER, AND ACTIVE FAST?")){state.logs=[];state.water=0;state.activeFast=null;save();initDashboard();toast("TODAY RESET ↻")}}}
function renderTimeline(box,items){if(!box)return;box.innerHTML=items.length?items.map(x=>`<div class="timeline-item"><span class="emoji">${x.emoji||"✦"}</span><div><b>${esc(x.name)}</b><small>${esc(x.detail||"")} · ${fmtTime(x.at)}</small></div><strong>${x.kind==="move"?`${Math.round(x.burn)} KCAL`:`${Math.round(x.nutrition?.calories||0)} KCAL`}</strong></div>`).join(""):'<div class="empty">NO LOGS YET — YOUR FIRST ONE WILL POP UP HERE ✨</div>'}

function initFoods(){initTimeDock();const all=allFoods(),select=$("#foodSelect"),search=$("#foodSearch");function fill(){const q=search.value.trim().toLowerCase(),items=all.filter(x=>(x.name+" "+(x.group||"")).toLowerCase().includes(q));select.innerHTML=foodSelectOptions(items);renderFoodPreview()}function renderFoodPreview(){const item=getFood(select.value)||all[0];if(!item)return;const mult=+$("#foodServings").value,n=scaleNutrition(nutritionOf(item),mult);$("#foodServingLabel").textContent=mult.toFixed(2).replace(/\.00$/,"")+"×";$("#foodPreview").innerHTML=`<div class="media-card"><img src="${imageFor(item)}" alt="${esc(item.name)}"><div class="card-body"><span class="eyebrow">${esc(item.group||"CCD FOOD")}</span><h3>${esc(item.name)}</h3>${nutritionCard(n,item)}</div></div>`}search.oninput=fill;select.onchange=renderFoodPreview;$("#foodServings").oninput=renderFoodPreview;fill();$("#logFood").onclick=()=>{const item=getFood(select.value);if(!item)return;const n=scaleNutrition(nutritionOf(item),+$("#foodServings").value),at=selectedTimestamp();state.logs.push({kind:"food",emoji:"🍽️",name:item.name,detail:`${$("#foodServings").value}× SERVING`,nutrition:n,at});state.xp+=15;save();toast("FOOD LOGGED +15 XP 🍽️")};initSotd();$("#quickFoods").innerHTML=(DATA.RECOVERED_FOOD_LOGS||[]).map(x=>`<article class="media-card"><img src="${imageFor(x)}" alt="${esc(x.name)}"><div class="card-body"><span class="eyebrow">QUICK LOG</span><h3>${esc(x.name)}</h3><p>${Math.round(nutritionOf(x).calories)} KCAL · ${esc(x.yieldText||"")}</p><button class="tiny-btn" data-quick-food="${esc(x.id)}">LOG IT ✦</button></div></article>`).join("");$$('[data-quick-food]').forEach(b=>b.onclick=()=>{const x=getFood(b.dataset.quickFood),n=nutritionOf(x);state.logs.push({kind:"food",emoji:"⚡",name:x.name,detail:"QUICK-LOG FAVORITE",nutrition:n,at:selectedTimestamp()});state.xp+=15;save();toast("QUICK FOOD LOGGED ✨")})}
function sotdNutrition(item,qty){const calories=item.calories*qty;return {calories,carbs:round(calories*.58/4,1),protein:round(calories*.07/4,1),fat:round(calories*.32/9,1),fiber:round(Math.max(0.5,calories/180),1),estimated:!item.recorded}}
function initSotd(){const list=DATA.SOTD_ITEMS||[],sel=$("#sotdSelect"),range=$("#sotdQty");sel.innerHTML=list.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join("");function update(){const x=list[+sel.value]||list[0];range.min=x.min;range.max=x.max;range.step=x.step;range.value=clamp(+range.value,x.min,x.max);$("#sotdQtyLabel").textContent=`${range.value} ${x.unit}${+range.value===1?"":"S"}`;const n=sotdNutrition(x,+range.value);$("#sotdPreview").innerHTML=`<div class="media-card"><img src="${x.image||IMAGE.snack}" alt="${esc(x.name)}"><div class="card-body"><h3>${esc(x.name)}</h3><p>${esc(x.note||"")}</p>${nutritionCard(n,x)}</div></div>`}sel.onchange=()=>{const x=list[+sel.value];range.value=x.min;update()};range.oninput=update;$("#randomSotd").onclick=()=>{sel.value=Math.floor(Math.random()*list.length);const x=list[+sel.value];range.value=x.min;update();toast("SOTD SHUFFLED ✨")};$("#logSotd").onclick=()=>{const x=list[+sel.value],q=+range.value,n=sotdNutrition(x,q);state.logs.push({kind:"food",emoji:x.emoji||"🍪",name:x.name,detail:`SOTD · ${q} ${x.unit}${q===1?"":"S"}`,nutrition:n,at:selectedTimestamp()});state.xp+=12;save();toast("SOTD LOGGED 🍪")};update()}

function initRecipes(){const all=allFoods(),grid=$("#recipeGrid"),search=$("#recipeSearch"),group=$("#groupFilter");const groups=[...new Set(all.map(x=>x.group||"OTHER"))].sort();group.innerHTML='<option value="all">ALL RECIPE GROUPS</option>'+groups.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");function render(){const q=search.value.toLowerCase(),g=group.value,items=all.filter(x=>(g==="all"||(x.group||"OTHER")===g)&&(x.name+" "+(x.group||"")).toLowerCase().includes(q));grid.innerHTML=items.slice(0,recipeVisible).map(x=>{const n=nutritionOf(x);return `<article class="recipe-card"><img loading="lazy" src="${imageFor(x)}" alt="${esc(x.name)}"><div class="card-body"><span class="eyebrow">${esc(x.group||"CCD")}</span><h3>${esc(x.name)}</h3><p>${Math.round(n.calories)} KCAL · ${round(n.protein,1)}G PROTEIN · ${round(n.fiber,1)}G FIBER</p><button class="tiny-btn" data-recipe="${esc(x.id)}">OPEN RECIPE ✦</button></div></article>`}).join("")||'<div class="empty">NO RECIPES MATCH THAT SEARCH.</div>';$("#loadMoreRecipes").hidden=recipeVisible>=items.length;$$('[data-recipe]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.recipe))}search.oninput=()=>{recipeVisible=20;render()};group.onchange=()=>{recipeVisible=20;render()};$("#loadMoreRecipes").onclick=()=>{recipeVisible+=20;render()};$("#randomRecipe").onclick=()=>openRecipe(all[Math.floor(Math.random()*all.length)].id);render();initRecipeLab();initUnitLab()}
function openRecipe(id){const item=getFood(id),d=$("#recipeDialog"),box=$("#recipeDialogBody");if(!item||!d)return;const n=nutritionOf(item),ingredients=item.ingredients?.length?item.ingredients:["ORIGINAL INGREDIENT QUANTITIES WERE NOT FULLY RECOVERED FOR THIS ARCHIVE ENTRY."],steps=item.steps?.length?item.steps:["OPEN THIS SAVED TITLE AS A STARTING POINT IN THE RECIPE LAB AND BUILD THE NEXT VERSION WITH PRESET PANTRY INGREDIENTS."];box.innerHTML=`<div class="dialog-inner"><div class="dialog-head"><div><span class="eyebrow">${esc(item.group||"CCD RECIPE")}</span><h2>${esc(item.name)}</h2><p>${esc(item.yieldText||"PERSONAL CCD RECIPE")}</p></div><button class="dialog-x" data-close>×</button></div><div class="dialog-hero"><img src="${imageFor(item)}" alt="${esc(item.name)}"><div>${nutritionCard(n,item)}<label class="range-label">SERVING SCALE <strong id="recipeScaleLabel">1×</strong><input id="recipeScale" type="range" min="0.5" max="4" step="0.5" value="1"></label><div id="recipeScaledMacros"></div></div></div><div class="split" style="margin-top:12px"><section><span class="eyebrow">VERTICAL INGREDIENT CHART</span><h3>INGREDIENTS</h3><ul class="ingredient-chart">${ingredients.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section><section><span class="eyebrow">METHOD</span><h3>DIRECTIONS</h3><div class="steps">${steps.map(x=>`<div>${esc(x)}</div>`).join("")}</div></section></div></div>`;const render=()=>{const m=+$("#recipeScale").value,s=scaleNutrition(n,m);$("#recipeScaleLabel").textContent=m+"×";$("#recipeScaledMacros").innerHTML=`<div class="bar-stack">${barHtml("CALORIES",s.calories,Math.max(500,s.calories)," KCAL")}${barHtml("CARBS",s.carbs,100)}${barHtml("PROTEIN",s.protein,50)}${barHtml("FAT",s.fat,50)}${barHtml("FIBER",s.fiber,20)}</div>`};$("#recipeScale").oninput=render;render();$('[data-close]',d).onclick=()=>d.close();d.showModal()}
function initRecipeLab(){const pantry=DATA.PANTRY||[],sel=$("#pantrySelect");sel.innerHTML=pantry.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · PER ${esc(x.unit)}</option>`).join("");function updateQty(){const x=pantry.find(p=>p.id===sel.value)||pantry[0];$("#pantryQtyLabel").textContent=`${$("#pantryQty").value} ${x?.unit||"UNIT"}`};sel.onchange=updateQty;$("#pantryQty").oninput=updateQty;$("#addIngredient").onclick=()=>{const x=pantry.find(p=>p.id===sel.value),qty=+$("#pantryQty").value;if(!x)return;studioIngredients.push({...x,qty});renderStudio();toast("INGREDIENT DROPPED INTO THE BOWL 🥣")};$("#studioServings").oninput=renderStudio;$("#mixRecipe").onclick=()=>{const bowl=$("#mixingBowl");bowl.classList.remove("mix");void bowl.offsetWidth;bowl.classList.add("mix");state.xp+=5;save();toast("MIXED! +5 XP 🎮")};$("#saveStudioRecipe").onclick=()=>{if(!studioIngredients.length)return toast("ADD INGREDIENTS FIRST 🥣");const total=studioIngredients.reduce((a,x)=>{a.calories+=x.calories*x.qty;a.carbs+=x.carbs*x.qty;a.protein+=x.protein*x.qty;a.fat+=x.fat*x.qty;a.fiber+=x.fiber*x.qty;return a},{calories:0,carbs:0,protein:0,fat:0,fiber:0}),serv=+$("#studioServings").value,name=`CUSTOM CCD LAB MIX ${state.studioRecipes.length+1}`;state.studioRecipes.push({id:"studio-"+Date.now(),name,group:"Saved Recipe Lab",source:"Berry Vibes Recipe Lab",ingredients:studioIngredients.map(x=>`${x.qty} ${x.unit} ${x.name}`),steps:["MIX THE SAVED PRESET INGREDIENTS UNTIL COMBINED.","COOK OR CHILL USING THE METHOD THAT FITS THE INGREDIENTS."],nutrition:scaleNutrition(total,1/serv),yieldText:`${serv} SERVING${serv===1?"":"S"}`});state.xp+=25;save();toast("CUSTOM RECIPE SAVED +25 XP 💾")};renderStudio();updateQty()}
function renderStudio(){const box=$("#studioIngredients");if(!box)return;$("#mixCount").textContent=studioIngredients.length+" ITEMS";box.innerHTML=studioIngredients.length?studioIngredients.map((x,i)=>`<div class="ingredient-chip"><b>${esc(x.name)}</b><span>${x.qty} ${esc(x.unit)}</span><button data-remove-ingredient="${i}">×</button></div>`).join(""):'<div class="empty">YOUR BOWL IS EMPTY — ADD A PRESET INGREDIENT.</div>';$$('[data-remove-ingredient]').forEach(b=>b.onclick=()=>{studioIngredients.splice(+b.dataset.removeIngredient,1);renderStudio()});const total=studioIngredients.reduce((a,x)=>{a.calories+=x.calories*x.qty;a.carbs+=x.carbs*x.qty;a.protein+=x.protein*x.qty;a.fat+=x.fat*x.qty;a.fiber+=x.fiber*x.qty;return a},{calories:0,carbs:0,protein:0,fat:0,fiber:0}),serv=+$("#studioServings").value||1,n=scaleNutrition(total,1/serv);$("#studioServingLabel").textContent=serv;$("#studioNutrition").innerHTML=`<div><span>KCAL / SERVING</span><b>${round(n.calories)}</b></div><div><span>CARBS</span><b>${round(n.carbs,1)}G</b></div><div><span>PROTEIN</span><b>${round(n.protein,1)}G</b></div><div><span>FIBER</span><b>${round(n.fiber,1)}G</b></div>`}
function initUnitLab(){const pantry=DATA.PANTRY||[],sel=$("#unitIngredient"),unit=$("#unitSelect"),amount=$("#unitAmount");sel.innerHTML=pantry.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");function update(){const x=pantry.find(p=>p.id===sel.value)||pantry[0],target=unit.value,amt=+amount.value,base=x.unit.toLowerCase();let mult=1;if(base==="tbsp")mult=target==="tsp"?1/3:target==="cup"?16:1;else if(base==="tsp")mult=target==="tbsp"?3:target==="cup"?48:1;const baseQty=amt*mult,n=scaleNutrition(x,baseQty);$("#unitResult").textContent=`${round(n.calories)} KCAL · ${round(n.carbs,1)}G C · ${round(n.protein,1)}G P · ${round(n.fat,1)}G F`}sel.onchange=update;unit.onchange=update;amount.oninput=update;update()}

function initMovement(){initTimeDock();const sel=$("#activitySelect"),range=$("#minutesRange");sel.innerHTML=MOVEMENTS.map(x=>`<option value="${x.id}">${x.emoji} ${esc(x.name)}</option>`).join("");function update(){const x=MOVEMENTS.find(m=>m.id===sel.value)||MOVEMENTS[0],mins=+range.value,burn=round(x.rate*mins);$("#minutesLabel").textContent=mins+" MIN";$("#movementPreview").innerHTML=`<div class="nutrition-card"><div class="nutrition-top"><span>${x.emoji} ${esc(x.name)}</span><strong>≈ ${burn} KCAL</strong></div><div class="taste-chart"><span>WHAT TO EXPECT</span><b>${esc(x.copy)}</b></div></div>`;$("#movementFactTitle").textContent=x.name;$("#movementFacts").innerHTML=movementFacts(x).map(v=>`<div>${v}</div>`).join("")}sel.onchange=update;range.oninput=update;$("#logMovement").onclick=()=>{const x=MOVEMENTS.find(m=>m.id===sel.value),mins=+range.value,burn=round(x.rate*mins);state.logs.push({kind:"move",emoji:x.emoji,name:x.name,detail:`${mins} MIN · AUTO ESTIMATE`,burn,at:selectedTimestamp()});state.xp+=20;save();toast("MOVEMENT LOGGED +20 XP ✨");renderMovementHistory()};function renderMovementHistory(){renderTimeline($("#movementHistory"),state.logs.filter(x=>x.kind==="move").slice().sort((a,b)=>b.at-a.at).slice(0,20))}update();renderMovementHistory()}
function movementFacts(x){return [`${x.emoji} ${x.name} = ${x.copy}`,`⏱️ THE EXACT-MINUTE SLIDER DRIVES THE BURN ESTIMATE — NO TYPING.`,`✨ MOVEMENT BURN STAYS SEPARATE FROM YOUR FOOD MAINTENANCE REFERENCE.`]}

function initFasting(){initTimeDock();const sel=$("#fastType");sel.innerHTML=(DATA.FAST_PRESETS||[]).map(x=>`<option value="${x.id}">${x.id} · ${x.hours} HOUR FAST</option>`).join("");function render(){const a=state.activeFast,box=$("#fastStatus");if(!a){box.innerHTML='<span>STATUS</span><strong>NO ACTIVE FAST</strong><p>PICK A STYLE AND START IT USING THE SELECTED TIME ABOVE.</p>'}else{const target=new Date(a.start+a.hours*3600000);box.innerHTML=`<span>ACTIVE ${esc(a.mode)}</span><strong>STARTED ${fmtTime(a.start)}</strong><p>TARGET BREAK TIME: ${target.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})} · ${fmtDate(target)}</p>`;sel.value=a.mode}$("#fastHistory").innerHTML=state.fastHistory.length?state.fastHistory.slice().reverse().slice(0,14).map(x=>`<div class="timeline-item"><span class="emoji">⏳</span><div><b>${esc(x.mode)} FAST</b><small>${fmtDate(x.start)} · ${fmtTime(x.start)} → ${fmtTime(x.end)}</small></div><strong>${round((x.end-x.start)/3600000,1)} H</strong></div>`).join(""):'<div class="empty">NO COMPLETED FASTS YET.</div>'}$("#fastStart").onclick=()=>{if(state.activeFast)return toast("A FAST IS ALREADY ACTIVE ⏳");const p=(DATA.FAST_PRESETS||[]).find(x=>x.id===sel.value);state.activeFast={mode:p.id,hours:p.hours,start:selectedTimestamp()};state.xp+=10;save();render();toast("FAST START LOGGED ⏳")};$("#fastStop").onclick=()=>{if(!state.activeFast)return toast("NO ACTIVE FAST TO BREAK");const end=selectedTimestamp(state.activeFast.start);state.fastHistory.push({...state.activeFast,end});state.activeFast=null;state.xp+=10;save();render();toast("FAST BREAK LOGGED ✨")};render()}

function initRestaurants(){initTimeDock();const chains=DATA.RESTAURANT_CHAINS||[],chain=$("#restaurantChain"),item=$("#restaurantItem"),portion=$("#restaurantPortion");chain.innerHTML=chains.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join("");function populate(){const c=chains[+chain.value]||chains[0];item.innerHTML=c.items.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join("");portion.value=1;preview()}function preview(){const c=chains[+chain.value],x=c?.items[+item.value];if(!x)return;const m=+portion.value,n=scaleNutrition({...x,estimated:!x.verified},m);$("#restaurantPortionLabel").textContent=m+"×";$("#restaurantPreview").innerHTML=`<div class="media-card"><img src="${c.image}" alt="${esc(c.name)}"><div class="card-body"><span class="eyebrow">${esc(c.name)}</span><h3>${esc(x.name)}</h3><p>${esc(c.source||"")}</p>${nutritionCard(n,x)}</div></div>`}chain.onchange=populate;item.onchange=preview;portion.oninput=preview;$("#logRestaurant").onclick=()=>{const c=chains[+chain.value],x=c.items[+item.value],n=scaleNutrition({...x,estimated:!x.verified},+portion.value);state.logs.push({kind:"food",emoji:"🍔",name:`${c.name} · ${x.name}`,detail:`RESTAURANT · ${portion.value}× PORTION`,nutrition:n,at:selectedTimestamp()});state.xp+=15;save();toast("RESTAURANT FOOD LOGGED 🍟")};$("#customRestaurantForm").onsubmit=e=>{e.preventDefault();const x={id:"restaurant-"+Date.now(),restaurant:$("#customRestaurant").value.trim(),name:$("#customFoodName").value.trim(),calories:+$("#customCalories").value,carbs:+$("#customCarbs").value,protein:+$("#customProtein").value,fat:+$("#customFat").value,fiber:+$("#customFiber").value,price:+$("#customPrice").value||0,image:$("#customImage").value.trim()||IMAGE.savory};state.customRestaurants.push(x);state.logs.push({kind:"food",emoji:"🍽️",name:`${x.restaurant} · ${x.name}`,detail:`CUSTOM RESTAURANT ITEM${x.price?` · $${x.price.toFixed(2)}`:""}`,nutrition:{...x,estimated:false},at:selectedTimestamp()});state.xp+=20;save();e.target.reset();renderCustomRestaurants();toast("CUSTOM RESTAURANT ITEM SAVED + LOGGED ✨")};$("#customRestaurantSearch").oninput=renderCustomRestaurants;populate();renderCustomRestaurants()}
function renderCustomRestaurants(){const box=$("#customRestaurantGrid");if(!box)return;const q=$("#customRestaurantSearch").value.toLowerCase();const list=state.customRestaurants.filter(x=>(x.restaurant+" "+x.name).toLowerCase().includes(q));box.innerHTML=list.length?list.map(x=>`<article class="media-card"><img src="${x.image||IMAGE.savory}" alt="${esc(x.name)}"><div class="card-body"><span class="eyebrow">${esc(x.restaurant)}</span><h3>${esc(x.name)}</h3><p>${x.calories} KCAL · ${round(x.protein,1)}G PROTEIN ${x.price?`· $${x.price.toFixed(2)}`:""}</p><button class="tiny-btn" data-log-custom="${x.id}">LOG AGAIN ✦</button></div></article>`).join(""):'<div class="empty">NO CUSTOM RESTAURANT ITEMS SAVED YET.</div>';$$('[data-log-custom]').forEach(b=>b.onclick=()=>{const x=state.customRestaurants.find(v=>v.id===b.dataset.logCustom);state.logs.push({kind:"food",emoji:"🍽️",name:`${x.restaurant} · ${x.name}`,detail:"CUSTOM RESTAURANT RE-LOG",nutrition:{...x,estimated:false},at:selectedTimestamp()});state.xp+=15;save();toast("CUSTOM ITEM LOGGED AGAIN ✨")})}

function battleScore(n){return round(n.protein*2.2+n.fiber*3.5+clamp((520-n.calories)*.035,-10,20),1)}
function initBattle(){const all=allFoods(),a=$("#battleA"),b=$("#battleB");a.innerHTML=foodSelectOptions(all);b.innerHTML=foodSelectOptions(all);if(all[1])b.value=all[1].id;function view(sel,box){const x=getFood(sel.value),n=nutritionOf(x);$(box).innerHTML=`<img src="${imageFor(x)}" alt="${esc(x.name)}" style="width:100%;height:220px;object-fit:cover;border-radius:18px;margin-top:10px"><h2>${esc(x.name)}</h2>${nutritionCard(n,x)}`}a.onchange=()=>view(a,"#battleAView");b.onchange=()=>view(b,"#battleBView");view(a,"#battleAView");view(b,"#battleBView");$("#battleButton").onclick=()=>{const A=getFood(a.value),B=getFood(b.value),na=nutritionOf(A),nb=nutritionOf(B),sa=battleScore(na),sb=battleScore(nb),winner=sa===sb?null:sa>sb?A:B;$("#battleResult").innerHTML=`<span class="winner-crown">${winner?"🏆":"🤝"}</span><h2>${winner?`${esc(winner.name)} WINS!`:"IT'S A TIE!"}</h2><p>${winner?"THE BALANCE SCORE EDGED OUT THE OTHER CONTENDER.":"THESE TWO LANDED ON THE SAME BALANCE SCORE."}</p><div class="battle-bars">${barHtml(A.name,sa,Math.max(sa,sb,1)," PTS")}${barHtml(B.name,sb,Math.max(sa,sb,1)," PTS")}${barHtml("A PROTEIN",na.protein,Math.max(na.protein,nb.protein,1))}${barHtml("B PROTEIN",nb.protein,Math.max(na.protein,nb.protein,1))}${barHtml("A FIBER",na.fiber,Math.max(na.fiber,nb.fiber,1))}${barHtml("B FIBER",nb.fiber,Math.max(na.fiber,nb.fiber,1))}</div>`;state.xp+=8;save()}}

function cartEntries(){const map=new Map();state.cart.forEach(x=>{const id=typeof x==="string"?x:x.id,qty=typeof x==="string"?1:+x.qty||1;if(SHOP_PRODUCTS.some(p=>p.id===id))map.set(id,(map.get(id)||0)+qty)});state.cart=[...map].map(([id,qty])=>({id,qty:clamp(Math.round(qty),1,99)}));return state.cart}
function toggleList(arr,id){const i=arr.indexOf(id);i>=0?arr.splice(i,1):arr.push(id);save()}
function addCart(id,qty=1){const items=cartEntries(),hit=items.find(x=>x.id===id);if(hit)hit.qty=clamp(hit.qty+qty,1,99);else items.push({id,qty:clamp(qty,1,99)});state.cart=items;save();shopCounts();toast(`ADDED ${qty} TO CART 🛍️`)}
function shopCounts(){const q=cartEntries().reduce((a,x)=>a+x.qty,0);if($("#cartCount"))$("#cartCount").textContent=q;if($("#wishlistCount"))$("#wishlistCount").textContent=state.wishlist.length;if($("#savedCount"))$("#savedCount").textContent=state.savedShop.length}
function initShop(){const search=$("#shopSearch"),cat=$("#shopCategory");cat.innerHTML='<option value="all">ALL CATEGORIES</option>'+[...new Set(SHOP_PRODUCTS.map(x=>x.category))].map(x=>`<option>${x}</option>`).join("");search.oninput=()=>renderShop();cat.onchange=()=>renderShop();$("#showWishlist").onclick=()=>renderShop("wish");$("#showSaved").onclick=()=>renderShop("saved");$("#openCart").onclick=openCart;renderShop();renderRecommendations();shopCounts()}
function renderShop(mode="all"){const q=$("#shopSearch").value.toLowerCase(),cat=$("#shopCategory").value;let list=SHOP_PRODUCTS.filter(x=>(cat==="all"||x.category===cat)&&(x.name+" "+x.category+" "+(x.character||"")).toLowerCase().includes(q));if(mode==="wish")list=list.filter(x=>state.wishlist.includes(x.id));if(mode==="saved")list=list.filter(x=>state.savedShop.includes(x.id));$("#shopGrid").innerHTML=list.length?list.map(x=>`<article class="shop-card"><img src="${x.image}" alt="${esc(x.name)}"><div class="card-body"><span class="eyebrow">${x.character||"BERRY BRUNCH"} · ${x.category}</span><h3>${esc(x.name)}</h3><p>${esc(x.desc)}</p><div class="price-row"><strong>$${x.price.toFixed(2)}</strong><span>DEMO ITEM</span></div><div class="qty-row"><span>QUANTITY</span><div class="qty-stepper"><button data-minus="${x.id}">−</button><b data-qty="${x.id}">1</b><button data-plus="${x.id}">+</button></div></div><div class="shop-actions"><button data-cart="${x.id}">ADD TO CART</button><button class="icon" data-wish="${x.id}">${state.wishlist.includes(x.id)?"♥":"♡"}</button><button class="icon" data-save="${x.id}">${state.savedShop.includes(x.id)?"🔖":"📑"}</button></div></div></article>`).join(""):'<div class="empty">NO SHOP ITEMS IN THIS VIEW.</div>';$$('[data-minus]').forEach(b=>b.onclick=()=>{const v=$(`[data-qty="${b.dataset.minus}"]`);v.textContent=Math.max(1,(+v.textContent||1)-1)});$$('[data-plus]').forEach(b=>b.onclick=()=>{const v=$(`[data-qty="${b.dataset.plus}"]`);v.textContent=Math.min(99,(+v.textContent||1)+1)});$$('[data-cart]').forEach(b=>b.onclick=()=>addCart(b.dataset.cart,+$(`[data-qty="${b.dataset.cart}"]`).textContent||1));$$('[data-wish]').forEach(b=>b.onclick=()=>{toggleList(state.wishlist,b.dataset.wish);renderShop(mode);renderRecommendations();shopCounts()});$$('[data-save]').forEach(b=>b.onclick=()=>{toggleList(state.savedShop,b.dataset.save);renderShop(mode);renderRecommendations();shopCounts()})}
function renderRecommendations(){const box=$("#shopRecommendations");if(!box)return;const engaged=[...cartEntries().map(x=>x.id),...state.wishlist,...state.savedShop],cats=engaged.map(id=>SHOP_PRODUCTS.find(p=>p.id===id)?.category).filter(Boolean);const list=SHOP_PRODUCTS.filter(x=>!engaged.includes(x.id)).sort((a,b)=>(cats.includes(b.category)?1:0)-(cats.includes(a.category)?1:0)).slice(0,4);box.innerHTML=list.map(x=>`<article class="media-card"><img src="${x.image}" alt="${esc(x.name)}"><div class="card-body"><span class="eyebrow">${x.character||"BERRY BRUNCH"} · ${x.category}</span><h3>${esc(x.name)}</h3><p>$${x.price.toFixed(2)}</p><button class="tiny-btn" data-rec="${x.id}">ADD 1 TO CART</button></div></article>`).join("");$$('[data-rec]').forEach(b=>b.onclick=()=>addCart(b.dataset.rec,1))}
function openCart(){const d=$("#cartDialog"),entries=cartEntries(),rows=entries.map(e=>({e,p:SHOP_PRODUCTS.find(p=>p.id===e.id)})).filter(x=>x.p),total=rows.reduce((a,x)=>a+x.p.price*x.e.qty,0);$("#cartDialogBody").innerHTML=`<div class="dialog-inner"><div class="dialog-head"><div><span class="eyebrow">BERRY CART</span><h2>YOUR CART</h2></div><button class="dialog-x" data-close>×</button></div><div class="shop-note">BERRY BRUNCH CHARACTER MERCH CONCEPTS ONLY · NO DANIELLE DESIGN WORK.</div>${rows.length?rows.map(({e,p})=>`<div class="cart-item"><img src="${p.image}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><small>QTY ${e.qty} · $${p.price.toFixed(2)} EACH</small></div><strong>$${(p.price*e.qty).toFixed(2)}</strong></div>`).join(""):'<div class="empty">YOUR CART IS EMPTY.</div>'}<div class="checkout-total grand"><span>PREVIEW TOTAL</span><strong>$${total.toFixed(2)}</strong></div><a class="btn primary wide" href="checkout.html" style="display:block;text-align:center;margin-top:10px">PROCEED TO CHECKOUT</a></div>`;$('[data-close]',d).onclick=()=>d.close();d.showModal()}
function initCheckout(){const rows=cartEntries().map(e=>({e,p:SHOP_PRODUCTS.find(p=>p.id===e.id)})).filter(x=>x.p),subtotal=rows.reduce((a,x)=>a+x.p.price*x.e.qty,0);$("#checkoutItems").innerHTML=rows.length?rows.map(({e,p})=>`<div class="checkout-item"><img src="${p.image}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><small>QTY ${e.qty} · $${p.price.toFixed(2)} EACH</small></div><strong>$${(p.price*e.qty).toFixed(2)}</strong></div>`).join(""):'<div class="empty">YOUR CART IS EMPTY. <a href="shop.html">GO BACK TO SHOP.</a></div>';$("#checkoutTotals").innerHTML=`<div class="checkout-total"><span>ITEMS</span><b>${rows.reduce((a,x)=>a+x.e.qty,0)}</b></div><div class="checkout-total grand"><span>PREVIEW TOTAL</span><b>$${subtotal.toFixed(2)}</b></div>`;$("#checkoutForm").onsubmit=e=>{e.preventDefault();if(!rows.length)return toast("YOUR CART IS EMPTY");const order="BV-"+Date.now().toString(36).toUpperCase();state.cart=[];save();e.target.hidden=true;$("#orderConfirmation").hidden=false;$("#orderConfirmation").innerHTML=`<div class="nutrition-card"><span class="eyebrow">ORDER PREVIEW CREATED</span><strong>${order}</strong><p>NO PAYMENT WAS COLLECTED. THIS IS A STATIC GITHUB DEMO CHECKOUT.</p><a href="shop.html" class="btn primary">BACK TO SHOP</a></div>`}}

function daySeed(extra=""){const d=new Date(),key=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}-${extra}`;let h=2166136261;for(const ch of key){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h)}
function dailyThree(pool,extra){const out=[],used=new Set();let seed=daySeed(extra);while(out.length<3&&out.length<pool.length){seed=(seed*1664525+1013904223)>>>0;const i=seed%pool.length;if(!used.has(i)){used.add(i);out.push(pool[i])}}return out}
function recipeFacts(item){const n=nutritionOf(item);const pool=[
  `🍓 ${item.name} LIVES IN ${item.group||"THE CCD ARCHIVE"}.`,
  `📊 ${Math.round(n.calories)} KCAL IN THE SAVED/ESTIMATED BASE PORTION · ${round(n.protein,1)}G PROTEIN · ${round(n.fiber,1)}G FIBER.`,
  `✨ EXPECT: ${tasteFor(item)}`,
  `🧪 THIS CARD CAN BE SCALED IN THE RECIPE VAULT WITHOUT RETYPING MACROS.`,
  `🎮 TRY IT IN FOOD BATTLE TO COMPARE ITS PROTEIN, FIBER, CALORIES, AND BALANCE SCORE.`,
  `📚 SOURCE: ${item.source||"RECOVERED CCD ARCHIVE"}.`,
  `🥄 ITS INGREDIENTS STAY IN A VERTICAL LIST; THE NUTRITION VISUALS STAY HORIZONTAL.`,
  `💾 LOGGING THIS FOOD SAVES THE SELECTED PORTION + TIME TO YOUR LOCAL DAILY HISTORY.`
];return dailyThree(pool,item.id||item.name)}
function movementDailyFacts(x){const pool=[
  `${x.emoji} ${x.name} = ${x.copy}`,
  `⏱️ THE EXACT-MINUTE SLIDER DRIVES THE BURN ESTIMATE — NO TYPING.`,
  `✨ MOVEMENT BURN STAYS SEPARATE FROM YOUR 2,100–2,150 KCAL MAINTENANCE REFERENCE.`,
  `🎮 PICK A NEW DURATION AND THE PREVIEW RE-CALCULATES INSTANTLY.`,
  `🕒 THE SCROLL-WHEEL TIME SELECTOR SAVES WHEN THE SESSION HAPPENED.`,
  `📈 ${x.name} USES A SAVED ESTIMATE OF ABOUT ${x.rate} KCAL PER MINUTE IN THIS PERSONAL LOGGING TOOL.`
];return dailyThree(pool,x.id)}
function initFacts(){const all=allFoods(),g=$("#factGroup"),q=$("#factSearch");const groups=[...new Set(all.map(x=>x.group||"OTHER"))].sort();g.innerHTML='<option value="all">ALL GROUPS</option>'+groups.map(x=>`<option>${esc(x)}</option>`).join("");function render(){const list=all.filter(x=>(g.value==="all"||(x.group||"OTHER")===g.value)&&(x.name+" "+(x.group||"")).toLowerCase().includes(q.value.toLowerCase()));$("#factGrid").innerHTML=list.slice(0,factVisible).map(x=>`<article class="fact-card"><span class="eyebrow">${esc(x.group||"CCD")}</span><h3>${esc(x.name)}</h3>${recipeFacts(x).map(f=>`<div>${esc(f)}</div>`).join("")}</article>`).join("");$("#loadMoreFacts").hidden=factVisible>=list.length}q.oninput=()=>{factVisible=24;render()};g.onchange=()=>{factVisible=24;render()};$("#loadMoreFacts").onclick=()=>{factVisible+=24;render()};render();$("#exerciseFacts").innerHTML=MOVEMENTS.map(x=>`<article class="fact-card"><span class="eyebrow">${x.emoji} MOVEMENT</span><h3>${esc(x.name)}</h3>${movementDailyFacts(x).map(v=>`<div>${esc(v)}</div>`).join("")}</article>`).join("")}

function initProfile(){const p=state.profile;$("#profileName").value=p.name||"";$("#profileHeight").value=p.height||"";$("#profileWeight").value=p.weight||"";$("#profileReason").value=p.reason||"";$("#accentColor").value=p.accent||"#ff4f8b";const preview=$("#profilePreview");if(p.photo){preview.style.backgroundImage=`url(${p.photo})`;preview.textContent=""}else{preview.style.backgroundImage="";preview.textContent="🍓"}$("#themeGrid").innerHTML=THEMES.map(t=>`<button class="theme-choice ${p.theme===t.id?"active":""}" data-theme="${t.id}" style="background:linear-gradient(135deg,${t.surface2},${t.accent})">${t.label}</button>`).join("");$$('[data-theme]').forEach(b=>b.onclick=()=>{p.theme=b.dataset.theme;const t=THEMES.find(x=>x.id===p.theme);p.accent=t.accent;save();applyTheme();initProfile()});$("#accentColor").oninput=e=>{p.accent=e.target.value;save();applyTheme()};$("#resetTheme").onclick=()=>{state.profile.theme="berry";state.profile.accent="#ff4f8b";save();applyTheme();initProfile()};$("#profilePic").onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2_500_000)return toast("USE AN IMAGE UNDER 2.5 MB");const r=new FileReader();r.onload=()=>{p.photo=r.result;save();initProfile();toast("PROFILE PHOTO SAVED ✨")};r.readAsDataURL(f)};$("#profileForm").onsubmit=e=>{e.preventDefault();p.name=$("#profileName").value.trim();p.height=$("#profileHeight").value.trim();p.weight=$("#profileWeight").value;p.reason=$("#profileReason").value.trim();save();toast("PROFILE SAVED 👤")}}

function readUsers(){try{return JSON.parse(localStorage.getItem(AUTH_USERS_KEY)||"[]")}catch{return []}}
function writeUsers(users){localStorage.setItem(AUTH_USERS_KEY,JSON.stringify(users))}
function initLogin(){
  const inTab=$("#signInTab"),upTab=$("#signUpTab"),inForm=$("#signInForm"),upForm=$("#signUpForm"),recovery=$("#recoveryPanel");
  function mode(m){const sign=m==="in";inTab.classList.toggle("active",sign);upTab.classList.toggle("active",!sign);inForm.hidden=!sign;upForm.hidden=sign;recovery.hidden=true}
  inTab.onclick=()=>mode("in");upTab.onclick=()=>mode("up");
  inForm.onsubmit=e=>{e.preventDefault();const id=$("#signInIdentity").value.trim().toLowerCase(),pw=$("#signInPassword").value,hit=readUsers().find(u=>(u.email===id||u.username===id)&&u.password===pw);if(!hit)return toast("NO LOCAL PROFILE MATCHED THAT LOGIN");localStorage.setItem(AUTH_SESSION_KEY,hit.email);state.profile.name=state.profile.name||hit.name;save();updateAuthChip();toast(`SIGNED IN AS ${hit.username||hit.name} ✨`)};
  upForm.onsubmit=e=>{e.preventDefault();const users=readUsers(),name=$("#signUpName").value.trim(),username=$("#signUpUsername").value.trim().toLowerCase(),email=$("#signUpEmail").value.trim().toLowerCase(),pw=$("#signUpPassword").value;if(users.some(u=>u.email===email))return toast("THAT LOCAL EMAIL IS ALREADY SAVED");if(users.some(u=>u.username===username))return toast("THAT USERNAME IS ALREADY SAVED");users.push({name,username,email,password:pw});writeUsers(users);localStorage.setItem(AUTH_SESSION_KEY,email);state.profile.name=state.profile.name||name;save();mode("in");updateAuthChip();toast("LOCAL PROFILE CREATED 🍓")};
  $("#forgotUsername").onclick=()=>{recovery.hidden=false;recovery.innerHTML=`<span class="eyebrow">FORGOT USERNAME</span><h3>FIND YOUR LOCAL USERNAME</h3><form id="usernameRecoveryForm" class="form-grid"><input id="recoveryEmail" class="span-2" type="email" placeholder="EMAIL USED ON THIS BROWSER" required><button class="btn secondary span-2">FIND USERNAME</button></form><div id="recoveryResult"></div>`;$("#usernameRecoveryForm").onsubmit=e=>{e.preventDefault();const email=$("#recoveryEmail").value.trim().toLowerCase(),hit=readUsers().find(u=>u.email===email);$("#recoveryResult").innerHTML=hit?`<div class="recovery-result">YOUR LOCAL USERNAME IS <strong>${esc(hit.username||hit.name)}</strong>.</div>`:`<div class="recovery-result">NO LOCAL ACCOUNT FOUND FOR THAT EMAIL ON THIS BROWSER.</div>`}};
  $("#forgotPassword").onclick=()=>{recovery.hidden=false;recovery.innerHTML=`<span class="eyebrow">RESET LOCAL PASSWORD</span><h3>CHANGE YOUR PASSWORD</h3><form id="passwordRecoveryForm" class="form-grid"><input id="recoveryIdentity" class="span-2" placeholder="EMAIL OR USERNAME" required><input id="newLocalPassword" class="span-2" type="password" minlength="6" placeholder="NEW PASSWORD · 6+ CHARACTERS" required><button class="btn berry span-2">SAVE NEW PASSWORD</button></form><div id="recoveryResult"></div>`;$("#passwordRecoveryForm").onsubmit=e=>{e.preventDefault();const id=$("#recoveryIdentity").value.trim().toLowerCase(),pw=$("#newLocalPassword").value,users=readUsers(),i=users.findIndex(u=>u.email===id||u.username===id);if(i<0){$("#recoveryResult").innerHTML=`<div class="recovery-result">NO LOCAL ACCOUNT FOUND ON THIS BROWSER.</div>`;return}users[i].password=pw;writeUsers(users);$("#recoveryResult").innerHTML=`<div class="recovery-result">LOCAL PASSWORD UPDATED. YOU CAN SIGN IN NOW. ✨</div>`}};
  $("#signOut").onclick=()=>{localStorage.removeItem(AUTH_SESSION_KEY);updateAuthChip();toast("SIGNED OUT")}
}

function init(){state=loadState();applyTheme();updateAuthChip();initInteractions();const p=document.body.dataset.page;const map={dashboard:initDashboard,foods:initFoods,recipes:initRecipes,movement:initMovement,fasting:initFasting,restaurants:initRestaurants,battle:initBattle,shop:initShop,checkout:initCheckout,facts:initFacts,profile:initProfile,login:initLogin};map[p]?.()}
document.addEventListener("DOMContentLoaded",init);
